#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
install_uat_unity.py - Instalador do UAT para jogos Unity.

Uso:
    python install_uat_unity.py "D:/caminho/para/o/jogo"

O script:
    1. Detecta a versao do Unity e runtime (Mono vs IL2CPP)
    2. Extrai BepInEx 5 (Mono) ou BepInEx 6 (IL2CPP) no diretorio do jogo
    3. Copia XUnity AutoTranslator + dependencias
    4. Copia o middleware + launcher + config default
    5. Cria start_translation.bat na raiz do jogo
    6. Pergunta idioma origem/destino e configura tudo

Requisitos: BepInEx_x64.zip e AutoTranslator.5.6.1.zip devem estar
em uat-unity/lib/ (ou serao buscados em jogos de referencia).
"""
import os
import sys
import shutil
import json
import subprocess
import struct
import zipfile

HERE = os.path.dirname(os.path.abspath(__file__))
LIB_DIR = os.path.join(HERE, "lib")

# Language list (same as launch_unity.py)
LANGUAGES = [
    ("en", "English"),
    ("pt", "Portugues (Brasil)"),
    ("pt-pt", "Portugues (Portugal)"),
    ("ja", "Japanese"),
    ("es", "Spanish"),
    ("fr", "French"),
    ("de", "German"),
    ("it", "Italian"),
    ("ko", "Korean"),
    ("zh", "Chinese"),
    ("ru", "Russian"),
]

LANG_MAP = {
    'pt': 'pt-BR', 'pt-BR': 'pt-BR', 'pt_BR': 'pt-BR', 'pb': 'pt-BR',
    'pt-pt': 'pt', 'pt_PT': 'pt', 'es': 'es', 'fr': 'fr', 'de': 'de',
    'ja': 'ja', 'zh': 'zh', 'ko': 'ko', 'ru': 'ru', 'it': 'it', 'en': 'en',
}

AUTOTRANSLATOR_CONFIG_TEMPLATE = """[Service]
Endpoint=CustomTranslate
FallbackEndpoint=GoogleTranslateV2

[General]
Language=pt-BR
FromLanguage=en

[Files]
Directory=Translation\\{Lang}\\Text
OutputFile=Translation\\{Lang}\\Text\\_AutoGeneratedTranslations.txt
SubstitutionFile=Translation\\{Lang}\\Text\\_Substitutions.txt
PreprocessorsFile=Translation\\{Lang}\\Text\\_Preprocessors.txt
PostprocessorsFile=Translation\\{Lang}\\Text\\_Postprocessors.txt

[TextFrameworks]
EnableIMGUI=False
EnableUGUI=True
EnableUIElements=True
EnableNGUI=True
EnableTextMeshPro=True
EnableTextMesh=False
EnableFairyGUI=True

[Behaviour]
MaxCharactersPerTranslation=400
IgnoreWhitespaceInDialogue=True
MinDialogueChars=20
ForceSplitTextAfterCharacters=0
CopytoClipboard=False
MaxClipboardCopyCharacters=2500
ClipboardDebounceTime=1.25
EnableUIResizing=True
EnableBatching=False
UseStaticTranslations=True
OverrideFont=
OverrideFontSize=
OverrideFontTextMeshPro=
FallbackFontTextMeshPro=
ResizeUILineSpacingScale=
ForceUIResizing=False
IgnoreTextStartingWith=\\u180e;
TextGetterCompatibilityMode=True
GameLogTextPaths=
RomajiPostProcessing=ReplaceMacronWithCircumflex;RemoveApostrophes;ReplaceHtmlEntities
TranslationPostProcessing=ReplaceMacronWithCircumflex;ReplaceHtmlEntities
RegexPostProcessing=
CacheRegexPatternResults=False
PersistRichTextMode=Final
CacheRegexLookups=False
CacheWhitespaceDifferences=False
GenerateStaticSubstitutionTranslations=False
GeneratePartialTranslations=False
EnableTranslationScoping=True
EnableSilentMode=True
BlacklistedIMGUIPlugins=
EnableTextPathLogging=False
OutputUntranslatableText=False
IgnoreVirtualTextSetterCallingRules=False
MaxTextParserRecursion=1
HtmlEntityPreprocessing=True
HandleRichText=True
EnableTranslationHelper=True
ForceMonoModHooks=False
InitializeHarmonyDetourBridge=False
RedirectedResourceDetectionStrategy=AppendMongolianVowelSeparatorAndRemoveAll
OutputTooLongText=False
TemplateAllNumberAway=False
ReloadTranslationsOnFileChange=False
DisableTextMeshProScrollInEffects=False
CacheParsedTranslations=False

[Texture]
TextureDirectory=Translation\\{Lang}\\Texture
EnableTextureTranslation=False
EnableTextureDumping=False
EnableTextureToggling=False
EnableTextureScanOnSceneLoad=False
EnableSpriteRendererHooking=False
LoadUnmodifiedTextures=False
DetectDuplicateTextureNames=False
DuplicateTextureNames=
EnableLegacyTextureLoading=False
TextureHashGenerationStrategy=FromImageName
CacheTexturesInMemory=True
EnableSpriteHooking=False

[ResourceRedirector]
PreferredStoragePath=Translation\\{Lang}\\RedirectedResources
EnableTextAssetRedirector=False
LogAllLoadedResources=False
EnableDumping=False
CacheMetadataForAllFiles=True

[Http]
UserAgent=
DisableCertificateValidation=True

[TranslationAggregator]
Width=400
Height=100
EnabledTranslators=

[Debug]
EnableConsole=False

[Migrations]
Enable=True
Tag=5.6.1

[Baidu]
BaiduAppId=
BaiduAppSecret=
DelaySeconds=1

[BingLegitimate]
OcpApimSubscriptionKey=

[Custom]
Url=http://127.0.0.1:5001
EnableShortDelay=False
DisableSpamChecks=False

[DeepL]
ExecutableLocation=
MinDelaySeconds=2
MaxDelaySeconds=6

[DeepLLegitimate]
ExecutableLocation=
ApiKey=
Free=False

[ezTrans]
InstallationPath=

[Google]
ServiceUrl=

[GoogleV2]
ServiceUrl=
RPCID=MkEWBc
VERSION=boq_translate-webserver_20210323.10_p0
UseSimplest=False

[GoogleLegitimate]
GoogleAPIKey=

[LecPowerTranslator15]
InstallationPath=

[LingoCloud]
LingoCloudToken=

[Watson]
Url=
Key=

[Yandex]
YandexAPIKey=
"""

def detect_unity_runtime(game_dir):
    """Detect Unity version and scripting runtime (Mono vs IL2CPP)."""
    data_dir = None
    for d in os.listdir(game_dir):
        if d.endswith("_Data") or d == "Data":
            data_dir = os.path.join(game_dir, d)
            break
    if not data_dir or not os.path.isdir(data_dir):
        return None, None
    has_managed = os.path.isdir(os.path.join(data_dir, "Managed"))
    has_mono = os.path.isdir(os.path.join(game_dir, "MonoBleedingEdge"))
    has_gameassembly = os.path.exists(os.path.join(game_dir, "GameAssembly.dll"))
    managed_assembly = os.path.exists(os.path.join(data_dir, "Managed", "Assembly-CSharp.dll"))

    if has_managed and managed_assembly:
        return "Mono", has_mono
    if has_gameassembly and not managed_assembly:
        return "IL2CPP", False
    if has_managed and has_mono:
        return "Mono", True
    return "Unknown", False

def get_unity_version(game_exe):
    """Try to read Unity version from the executable (for Mono games, check data folder)."""
    data_dir = None
    for d in os.listdir(os.path.dirname(game_exe)):
        if d.endswith("_Data"):
            data_dir = os.path.join(os.path.dirname(game_exe), d)
            break
    if data_dir:
        global_game_managers = os.path.join(data_dir, "globalgamemanagers")
        if os.path.exists(global_game_managers):
            try:
                with open(global_game_managers, 'rb') as f:
                    data = f.read()
                    # Search for Unity version string
                    idx = data.find(b'Unity ')
                    if idx != -1:
                        version = data[idx:idx+30].split(b'\x00')[0].decode('utf-8', errors='replace')
                        return version
            except:
                pass
    return "unknown"

def find_game_exe(game_dir):
    exes = []
    for f in os.listdir(game_dir):
        if f.endswith('.exe') and f.lower() not in ('unitycrashhandler64.exe', 'unityplayer.dll',
                                                      'bpxprocess.exe', 'steam.exe', 'steamservice.exe'):
            exes.append(f)
    if exes:
        exes.sort(key=lambda x: len(x))
        return os.path.join(game_dir, exes[0])
    return None

def extract_zip(zip_path, dest):
    with zipfile.ZipFile(zip_path, 'r') as z:
        z.extractall(dest)

def choose_language(title, default=None):
    print(f"\n  {title}")
    for i, (code, name) in enumerate(LANGUAGES, 1):
        marker = " (atual)" if default == code else ""
        print(f"    [{i:>2}] {name} ({code}){marker}")
    print("    [ 0] Digitar codigo manualmente")
    def_idx = 2 if default in ('pt', 'pt-BR') else 1
    while True:
        try:
            raw = input(f"  Escolha [1-11] (padrao={def_idx}): ").strip()
            if raw == '0':
                code = input("  Codigo do idioma: ").strip().lower()
                return code
            val = int(raw) if raw else def_idx
            if 1 <= val <= len(LANGUAGES):
                return LANGUAGES[val - 1][0]
        except ValueError:
            pass
        print("  Invalido.")

def main():
    if len(sys.argv) < 2:
        print("Uso: python install_uat_unity.py \"caminho/para/o/jogo\"")
        print("\nExemplos:")
        print("  python install_uat_unity.py \"D:/Games/MyGame\"")
        print("  python install_uat_unity.py \"D:/Games/MyGame\" src=en tgt=pt-BR")
        sys.exit(1)

    game_dir = os.path.abspath(sys.argv[1])

    # Parse args
    src = None
    tgt = None
    for arg in sys.argv[2:]:
        if arg.startswith("src="):
            src = arg[4:]
        elif arg.startswith("tgt="):
            tgt = arg[4:]

    if not os.path.isdir(game_dir):
        print(f"[ERRO] Diretorio nao existe: {game_dir}")
        sys.exit(1)

    game_exe = find_game_exe(game_dir)
    if not game_exe:
        print(f"[ERRO] Nenhum .exe de jogo encontrado em: {game_dir}")
        sys.exit(1)

    print(f"\n[OK] Jogo encontrado: {os.path.basename(game_exe)}")
    print(f"     Diretorio: {game_dir}")

    # Detect runtime
    runtime, has_mono = detect_unity_runtime(game_dir)
    unity_ver = get_unity_version(game_exe)
    print(f"     Unity: {unity_ver}")
    print(f"     Runtime: {runtime} (MonoBleedingEdge: {has_mono})")

    if runtime == "IL2CPP":
        print("\n[ERRO] Jogos IL2CPP necessitam de BepInEx 6 / UnityDoorstop.")
        print("       Este instalador suporta apenas jogos Mono por enquanto.")
        print("       Para IL2CPP, instale manualmente BepInEx 6 e depois")
        print("       copie os arquivos de uat-unity/ manualmente.")
        sys.exit(1)

    if runtime == "Unknown":
        print("\n[AVISO] Nao foi possivel detectar o runtime. Tentando Mono (padrao)...")

    bepinex_dir = os.path.join(game_dir, "BepInEx")
    if os.path.exists(os.path.join(bepinex_dir, "core")):
        print(f"\n[INFO] BepInEx ja instalado em: {bepinex_dir}")
    else:
        # Install BepInEx
        bepinex_zip = os.path.join(LIB_DIR, "BepInEx_x64.zip")
        if not os.path.exists(bepinex_zip):
            print(f"\n[ERRO] BepInEx_x64.zip nao encontrado em: {LIB_DIR}")
            print("       Baixe de https://github.com/BepInEx/BepInEx/releases")
            print(f"       e coloque em: {bepinex_zip}")
            sys.exit(1)
        print(f"\n[INFO] Instalando BepInEx 5 de: {bepinex_zip}")
        extract_zip(bepinex_zip, game_dir)
        print("[OK] BepInEx instalado.")

    # Install AutoTranslator
    at_dir = os.path.join(bepinex_dir, "plugins", "XUnity.AutoTranslator")
    if os.path.exists(at_dir):
        print(f"\n[INFO] AutoTranslator ja instalado.")
    else:
        at_zip = os.path.join(LIB_DIR, "AutoTranslator.5.6.1.zip")
        if os.path.exists(at_zip):
            print(f"\n[INFO] Instalando AutoTranslator de: {at_zip}")
            extract_zip(at_zip, os.path.join(bepinex_dir, "plugins"))
        else:
            # Try copying from a reference game
            ref_dir = None
            for d in os.listdir("D:\\Compactados"):
                for sub in os.listdir(f"D:\\Compactados\\{d}"):
                    candidate = f"D:\\Compactados\\{d}\\{sub}\\BepInEx\\plugins\\XUnity.AutoTranslator"
                    if os.path.isdir(candidate):
                        ref_dir = candidate
                        break
                if ref_dir:
                    break
            if ref_dir:
                print(f"\n[INFO] Copiando AutoTranslator de referencia: {ref_dir}")
                dst = os.path.join(bepinex_dir, "plugins", "XUnity.AutoTranslator")
                shutil.copytree(ref_dir, dst)
            else:
                print(f"\n[ERRO] AutoTranslator.5.6.1.zip nao encontrado em {LIB_DIR}")
                print("       Baixe de https://github.com/Imholcns/XUnity-AutoTranslator/releases")
                sys.exit(1)
        print("[OK] AutoTranslator instalado.")

    # Copy XUnity.Common.dll if missing
    common_dll = os.path.join(bepinex_dir, "core", "XUnity.Common.dll")
    if not os.path.exists(common_dll):
        ref_dll = None
        for root, dirs, files in os.walk("D:\\Compactados"):
            if "XUnity.Common.dll" in files:
                ref_dll = os.path.join(root, "XUnity.Common.dll")
                break
        if ref_dll:
            print(f"[OK] Copiando XUnity.Common.dll da referencia...")
            shutil.copy2(ref_dll, common_dll)

    # Launcher + middleware sao compartilhados em uat-unity/ (HERE).
    # Nao sao copiados para o jogo; start_translation.bat aponta para HERE.
    mw_src = os.path.join(HERE, "libretranslate_middleware.py")
    launcher_src = os.path.join(HERE, "launch_unity.py")
    if not os.path.exists(mw_src) or not os.path.exists(launcher_src):
        print(f"\n[ERRO] Arquivos compartilhados nao encontrados em: {HERE}")
        sys.exit(1)
    print("[OK] Launcher + middleware compartilhados (uat-unity/).")

    # Language selection
    print("\n" + "=" * 56)
    print("  Configuracao de idiomas")
    print("=" * 56)
    if not src:
        src = choose_language("Idioma original do jogo:", default="en")
    if not tgt:
        tgt = choose_language("Traduzir para:", default="pt-BR")

    tgt_mapped = LANG_MAP.get(tgt, tgt)
    print(f"\n  Origem: {src}")
    print(f"  Destino: {tgt} (Argos: {tgt_mapped})")

    # Save per-game config
    config_file = os.path.join(game_dir, "unity_uat_config.json")
    with open(config_file, 'w', encoding='utf-8') as f:
        json.dump({"source_language": src, "target_language": tgt}, f, ensure_ascii=False, indent=2)
    print(f"[OK] Config salvo em: {config_file}")

    # Create/update AutoTranslatorConfig.ini
    config_dir = os.path.join(bepinex_dir, "config")
    config_path = os.path.join(config_dir, "AutoTranslatorConfig.ini")
    from_lang = src if src != 'auto' else 'en'
    content = AUTOTRANSLATOR_CONFIG_TEMPLATE
    content = content.replace("FromLanguage=en", f"FromLanguage={from_lang}")
    content = content.replace("Language=pt-BR", f"Language={tgt}")
    content = content.replace("Url=http://127.0.0.1:5001", "Url=http://127.0.0.1:5001")
    with open(config_path, 'w', encoding='utf-8') as f:
        f.write(content)
    print(f"[OK] AutoTranslatorConfig.ini atualizado para {src} -> {tgt}")

    # Create start_translation.bat (aponta para o launcher compartilhado)
    bat_path = os.path.join(game_dir, "start_translation.bat")
    game_name = os.path.basename(game_exe)
    launcher_path = os.path.join(HERE, "launch_unity.py")
    bat_content = f"""@echo off
cd /d "%~dp0"
python "{launcher_path}" "%~dp0" src={src} tgt={tgt}
"""
    with open(bat_path, 'w') as f:
        f.write(bat_content)
    print(f"[OK] start_translation.bat criado.")

    # Run once to generate BepInEx configs
    print("\n[INFO] Rodando o jogo uma vez para gerar configs (fechar logo após)...")
    try:
        proc = subprocess.Popen([game_exe], cwd=game_dir)
        import time
        time.sleep(15)
        if proc.poll() is None:
            proc.terminate()
            try:
                proc.wait(timeout=10)
            except:
                proc.kill()
        print("[OK] Configs geradas.")
    except Exception as e:
        print(f"[AVISO] Nao foi possivel rodar o jogo para gerar configs: {e}")

    print("\n" + "=" * 56)
    print("  INSTALACAO CONCLUIDA!")
    print("=" * 56)
    print(f"\n  Jogo: {game_name}")
    print(f"  Idioma: {src} -> {tgt}")
    print(f"\n  Para jogar com traducao:")
    print(f"    1. Execute: start_translation.bat")
    print(f"    2. Ou: python launch_unity.py \"{game_dir}\" src={src} tgt={tgt}")
    print(f"\n  Traducao: LibreTranslate local (sem rate limit)")
    print(f"  Endpoint middleware: http://127.0.0.1:5001")
    print(f"\n  Cache: {os.path.join(bepinex_dir, 'Translation', tgt, 'Text')}")

    return 0

if __name__ == "__main__":
    sys.exit(main())
